name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
   build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]

    steps:
      - run: echo "${{ github.event_name }} event, running on a ${{ runner.os }}."
      - run: echo "Branch ${{ github.ref }}, Repository ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository was cloned."
  
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Display dotnet version
        run: dotnet --version

      - name: Install ReSharper CLI tools
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Code Cleanup
        run: jb cleanupcode CleanCode.sln

      - name: Code Inspect
        run: jb inspectcode CleanCode.sln -f="sarif" -o=CodeIssues.json

      - name: Display Code Inspect result
        run: |
          cat CodeIssues.json

      - name: Test
        run: dotnet test

      - run: echo "Job status ${{ job.status }}."
